### ISSUE TITLE
list of selected_markers 

### ISSUE THREAD

**Issue by kaizen89** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#1]
Hi,
Congratulations for the preprint.
Would it be possible to share the list of the selected_markers that were dataset specific?
Thank you

**Comment by PaulaNietoG** [comment]
Hello, thanks for your interest in our project and sorry for taking too long to reply! This is the full list of the dataset-specific markers (p_val_adj < 0.05): [dataset_markers.zip](https://github.com/Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas/files/5545601/dataset_markers.zip) hope you find it useful
