### ISSUE TITLE
Issue of combining raw counts and normalized counts

### ISSUE THREAD

**Issue by hurleyLi** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#11]
Hi, thanks for the preprints, I really enjoyed reading it! 
I noticed that in your preprints you combined different studies with either raw counts or normalized counts. I'm wondering if that'll break any pre-assumptions from Seurat's anchor approach. I'm working on combining different sets of data related to immunology diseases, and have the same issue where some studies provided raw counts and some provided normalized counts... 
I know you mentioned in #10 that those are the "best" you could get, but it still needs to be accurate. I'm wondering whether we should process from the raw fastq files to get the actual raw count matrix for those only provided normalized matrix.

Thanks,
Hurley

**Comment by PaulaNietoG** [comment]
Hi Hurley, sorry for the late reply!
Yes, absolutely the best you can do is process the raw fastq files.

Paula
