### ISSUE TITLE
error when loading TICAtlas.h5ad data

### ISSUE THREAD

**Issue by Byronxy** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#2]
Hi,
I download the data from zenodo while I find the error when load data.
1. load data in R
I use the following code:
```
Convert("~/software/TICAtlas.h5ad", dest = "h5seurat", overwrite = TRUE)
TICAtlas <- LoadH5Seurat("~/software/TICAtlas.h5seurat")
```
The error is 
`
Validating h5Seurat file
Initializing RNA with data
Adding counts for RNA
Adding scale.data for RNA
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
`

2. load data in python
I use the following code:
```
import scanpy as sc
adata = sc.read_h5ad("/export/bioinfo-team/home/xiongy/software/TICAtlas.h5ad")
```
The error is 
`ValueError: Variables annot. `var` must have number of columns of `X` (5000), but has 4997 rows.`

**Comment by sialindskrog** [comment]
I got the same error.

However, it worked when only including the count and data assays (excluding the scale.data assay): 
tica <- LoadH5Seurat("/Data/TICAtlas.h5seurat", assays = c("counts", "data"))

But a solution to load the entire dataset would of course be optimal.

**Comment by PaulaNietoG** [comment]
Hi! Thanks for letting us know! We are working on fixing this as soon as possible

**Comment by PaulaNietoG** [comment]
This should now be fixed in the latest Zenodo upload (https://doi.org/10.5281/zenodo.4036019)
