### ISSUE TITLE
TICAtlas.h5ad cell type metadata contains only integers

### ISSUE THREAD

**Issue by adamgayoso** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#3]
Would it be possible to upload the anndata with the correct string cell type values?

Thanks!

**Comment by PaulaNietoG** [comment]
Hello, thanks for pointing this out! I believe this has to do with how scanpy reads h5ad files (more specifically, factors), as this doesn't happen with Seurat. I will try to convert all metadata factor variables to strings/characters and will ket you know so you can download the file again.

**Comment by PaulaNietoG** [comment]
Maybe in the meantime you could do this someone sent me:

<img width="878" alt="Screenshot 2020-11-09 at 11 57 46" src="https://user-images.githubusercontent.com/36140522/98544045-afce4580-2293-11eb-8b10-463f339d1e40.png">

**Comment by PaulaNietoG** [comment]
This should be fixed now.
