### ISSUE TITLE
TICAtlas.h5ad anndata raw attribute

### ISSUE THREAD

**Issue by adamgayoso** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#4]
Hello,

It would be helpful if there was description of the difference between the `.X` attribute and what is stored in `.raw.X`.

**Comment by PaulaNietoG** [comment]
Hi! Sorry, I am not super familiarized with h5ad/anndata formats, but I believe `.raw.X` contains the raw counts and `.X` contains the normalized counts (the equivalent to Seurat's data slot). Hope this helped!

**Comment by adamgayoso** [comment]
Thanks!
