### ISSUE TITLE
list of features used for integration

### ISSUE THREAD

**Issue by adamgayoso** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#5]
Would it be possible to supply the list of features used for integration without having to run the scripts provided here?

Thanks!

**Comment by PaulaNietoG** [comment]
Hello and sorry for the delay! Here you have the integration features: 
[integration_features.csv.gz](https://github.com/Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas/files/6172352/integration_features.csv.gz)
