### ISSUE TITLE
 markers for immune cell types

### ISSUE THREAD

**Issue by harryzs** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#7]
Dear Paula Nieto, Holger Heyn and others.

with great interest I read your preprint at biorxiv. 

Thanks for your great work on this project.

Would it be possible to share <Supplemental Table 2> and <Supplemental Table 3> mentioned in your preprint?

Thanks!

**Comment by PaulaNietoG** [comment]
[Supplementary_Table3.xlsx](https://github.com/Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas/files/6172375/Supplementary_Table3.xlsx)
[Supplementary_Table2.xlsx](https://github.com/Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas/files/6172376/Supplementary_Table2.xlsx)
Here you have them! Sorry for the delay, I totally missed your issue!
