### ISSUE TITLE
Immune reference files are not found

### ISSUE THREAD

**Issue by matemanc** [Single-Cell-Genomics-Group-CNAG-CRG/Tumor-Immune-Cell-Atlas#8]
Dear Paula Nieto,

First, let me congratulate you on your excellent preprint. I am very glad to have the code for spatial breast cancer transcriptomics as I would like to test the relationship between the expression of certain genes and the prevalence of immune cells. However, I cannot find the following files anywhere: "atlas_250_specific_cell_type.rds", "atlas_complete_annotation_breast.rds", "atlas_complete_annotation_melanoma.rds". Is it possible to have these files?

Thank you very much and best wishes,

Máté Manczinger

**Comment by PaulaNietoG** [comment]
Dear Máté,
Thanks a lot for your interest in our work! The files you mention are just subsets of the atlas that we used for specific tasks (250 cells per cell type, only melanoma or only breast cancer subsets). You can download the full atlas from [Zenodo](https://zenodo.org/record/4263972#.YFTD869KiHs) and subset the object yourself, as uploading big files here is complicated.
Hope this helps!
